import test from 'node:test';
import assert from 'node:assert/strict';
import {freshState,restore,doAction,purchase,moveFriend,completeQuest,claimQuests,QUESTS} from '../app/src/main/assets/game/model.mjs';
test('a new world has four friends and separate room positions',()=>{const s=freshState();assert.equal(s.friends.length,4);moveFriend(s,'mochi',-5,900);assert.deepEqual(s.friends[0].positions.home,{x:90,y:610});assert.deepEqual(s.friends[0].positions.cafe,{x:355,y:565});});
test('care improves needs, caps values and completes the matching wish',()=>{const s=freshState();doAction(s,'mochi','feed');assert.equal(s.friends[0].hunger,96);assert.ok(s.questDone.includes('feed'));doAction(s,'mochi','feed');assert.equal(s.friends[0].hunger,100);for(let i=0;i<20;i++)doAction(s,'mochi','feed');const coins=s.coins;doAction(s,'mochi','feed');assert.equal(s.coins,coins);});
test('purchases charge once and cannot overdraw',()=>{const s=freshState();assert.equal(purchase(s,'lights'),false);assert.equal(purchase(s,'rug'),true);assert.equal(s.coins,10);assert.equal(purchase(s,'rug'),false);assert.equal(purchase(s,'bogus'),false);});
test('quest reward requires all wishes and pays only once',()=>{const s=freshState();assert.equal(claimQuests(s),false);QUESTS.forEach(q=>completeQuest(s,q.id));assert.equal(claimQuests(s),true);assert.equal(s.coins,70);assert.equal(claimQuests(s),false);assert.equal(s.coins,70);});
test('save round trip preserves customization, progress and room positions',()=>{const s=freshState();s.room='garden';s.selected='pip';s.started=true;s.friends[1].hat='flower';s.plant={stage:1,readyAt:Date.now()+10000};moveFriend(s,'pip',999,500);purchase(s,'rug');assert.deepEqual(restore(JSON.stringify(s)),s);});
test('bad or outdated saves recover safely and numeric values are bounded',()=>{assert.deepEqual(restore('broken'),freshState());assert.deepEqual(restore('{"version":9}'),freshState());const s=restore(JSON.stringify({version:1,coins:-100,room:'secret',selected:'unknown',decor:['rug','rug','bad'],friends:[{id:'mochi',hunger:500,hat:'invalid',positions:{home:{x:-1000,y:990}}}]}));assert.equal(s.coins,0);assert.equal(s.room,'home');assert.equal(s.friends[0].hunger,100);assert.deepEqual(s.friends[0].positions.home,{x:90,y:610});assert.deepEqual(s.decor,['rug']);});
